Dataflow | Getting the data from prescription api from omod and adding column to LinkedAccounts table
Bahmni-Covid19/hip-service pull request #37
Opened 2020-12-17 12:36 UTC by MeghnaThoughtworks

2020-12-21 06:31 UTC, praveenadayanand requested changes

2020-12-21 06:31 UTC, praveenadayanand commented on abc.patch
> +diff --git a/docker-compose.yml b/docker-compose.yml
Please remove file from the commit

2020-12-21 06:31 UTC, praveenadayanand commented on docker-compose.yml
> +      - OpenMrs:url=https://192.168.33.10/openmrs/
Update the URL to use a variable instead of a specific ip-address and update teh readme on how to connect HIP service with local Bahmni vagrant

2020-12-21 06:31 UTC, praveenadayanand commented on src/In.ProjectEKA.HipLibrary/Patient/Model/ErrorCode.cs
> +    {
Commit not needed

2020-12-21 06:31 UTC, praveenadayanand commented on src/In.ProjectEKA.HipLibrary/Patient/Model/DataRequest.cs
> +        public DataRequest(
Commit not needed

2020-12-21 06:31 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/Consent/ConsentNotificationController.cs
> +        // [HttpPost(PATH_CONSENTS_HIP)]
Remove commented line

2020-12-21 06:31 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/DataFlow/CollectHipService.cs
> +                "yyyy-MM-dd"/*, "yyyy-MM-dd hh:mm:ss", "yyyy-MM-dd hh:mm:ss tt", "yyyy-MM-ddTHH:mm:ss.fffzzz",
Verify if this change is valud

2020-12-21 06:31 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/DataFlow/CollectHipService.cs
> +        private async Task<Dictionary<string, List<string>>> FindPatientData(TraceableDataRequest request)
Please check if the build warning can be rectified

2020-12-21 06:31 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/DataFlow/MessagingQueueConstants.cs
> +        public static readonly string DataRequestRoutingKey = "*.queue.durable.dataflowrequest5.#";
?

2020-12-21 06:31 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/DataFlow/OpenMrsPatientData.cs
> +            if(root.GetProperty("prescriptions").GetArrayLength() > 0 ) {
Can we use constant for "prescriptions" ?

2020-12-21 06:31 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/DataFlow/OpenMrsPatientData.cs
> +                    path = pathForOpenMRSPrescription(patientUuid, grantedContext, toDate, fromDate);
I think the whole data fetch logic for a particular hi-type should go inside a method, i.e, the json parsing and looking up of ex. prescription. the pathForOpenMRSPrescription could then become getPrescription. The reason I say this, when we move on tot he next hi-type, we can just update teh getDiagnosticReport, etc methods and not modify the getPatientData method at all

2020-12-21 06:31 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/DataFlow/OpenMrsPatientData.cs
> +                query["toDate"] = DateTime.Parse(toDate).AddDays(2).ToString("yyyy-MM-dd");
The prescription endpoint in HIP-OMOD does not include the end date in the input date range. To overcome this limitation two days are added. Is this relevant now?

2020-12-21 06:31 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/Discovery/PatientController.cs
> +        // [HttpPost(PATH_CARE_CONTEXTS_DISCOVER)]
Commented code

2020-12-21 06:31 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/Link/Database/Migrations/LinkPatientContextModelSnapshot.cs
> +    partial class LinkPatientContextModelSnapshot : ModelSnapshot
?

2020-12-21 06:31 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/Link/Database/Migrations/LinkPatientContextModelSnapshot.cs
>              modelBuilder
Please verify the editor formatting matches, else the changes shown are lot more than the actual code change

2020-12-21 06:31 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/OpenMrs/OpenMrsClient.cs
> +                if (error.Length > 100)
Is this change relevant?

2020-12-21 06:31 UTC, praveenadayanand commented on test/In.ProjectEKA.HipServiceTest/DataFlow/CollectHipServiceTest.cs
> +            // entries.ValueOrDefault().CareBundles.Count().Should().Be(17);
?

2020-12-21 11:27 UTC, Nazeer-debug commented on src/In.ProjectEKA.HipService/Link/Database/Migrations/LinkPatientContextModelSnapshot.cs
> +    partial class LinkPatientContextModelSnapshot : ModelSnapshot
It's an automatic db migration change

2020-12-21 11:27 UTC, Nazeer-debug commented on src/In.ProjectEKA.HipService/Link/Database/Migrations/LinkPatientContextModelSnapshot.cs
>              modelBuilder
Same reason as above

2020-12-21 11:38 UTC, Nazeer-debug commented on src/In.ProjectEKA.HipService/DataFlow/MessagingQueueConstants.cs
> +        public static readonly string DataRequestRoutingKey = "*.queue.durable.dataflowrequest5.#";
It throws a resource allocation exception related to queues if we don't keep on changing the number

2020-12-22 06:08 UTC, MeghnaThoughtworks commented on abc.patch
> +diff --git a/docker-compose.yml b/docker-compose.yml
done

2020-12-22 06:08 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipLibrary/Patient/Model/DataRequest.cs
> +        public DataRequest(
Indentation was wrong

2020-12-22 06:09 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/Consent/ConsentNotificationController.cs
> +        // [HttpPost(PATH_CONSENTS_HIP)]
done

2020-12-22 06:09 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/DataFlow/CollectHipService.cs
> +                "yyyy-MM-dd"/*, "yyyy-MM-dd hh:mm:ss", "yyyy-MM-dd hh:mm:ss tt", "yyyy-MM-ddTHH:mm:ss.fffzzz",
corrected

2020-12-22 06:09 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/DataFlow/OpenMrsPatientData.cs
> +            if(root.GetProperty("prescriptions").GetArrayLength() > 0 ) {
done

2020-12-22 06:09 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/DataFlow/OpenMrsPatientData.cs
> +                    path = pathForOpenMRSPrescription(patientUuid, grantedContext, toDate, fromDate);
done

2020-12-22 06:09 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/DataFlow/OpenMrsPatientData.cs
> +                query["toDate"] = DateTime.Parse(toDate).AddDays(2).ToString("yyyy-MM-dd");
done

2020-12-22 06:09 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/Discovery/PatientController.cs
> +        // [HttpPost(PATH_CARE_CONTEXTS_DISCOVER)]
done

2020-12-22 06:10 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/OpenMrs/OpenMrsClient.cs
> +                if (error.Length > 100)
done

2020-12-22 10:10 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipLibrary/Patient/Model/ErrorCode.cs
> +    {
done

2020-12-22 10:10 UTC, MeghnaThoughtworks commented on test/In.ProjectEKA.HipServiceTest/DataFlow/CollectHipServiceTest.cs
> +            // entries.ValueOrDefault().CareBundles.Count().Should().Be(17);
done

2020-12-31 08:56 UTC, merged