#90\Meghna | Changes the discovery to use new CareContext OMOD api
Bahmni-Covid19/hip-service pull request #39
Opened 2021-01-05 15:34 UTC by MeghnaThoughtworks

2021-01-05 17:31 UTC, praveenadayanand requested changes

2021-01-05 17:31 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/OpenMrs/OpenMrsCareContextRepository.cs
> +                switch (careContextType)
Are these steps needed? A straightforward copying of carecontexts from the JSON would be enough, isnt it ?

2021-01-08 04:44 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/OpenMrs/OpenMrsCareContextRepository.cs
> +                switch (careContextType)
Yeah cause right now for VISIT_TYPE the type is getting stored in "reference number" and program in "display". There is refactoring needed in the whole flow to correct this.

2021-01-08 06:55 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/OpenMrs/OpenMrsCareContextRepository.cs
> +                switch (careContextType)
done

2021-01-12 10:27 UTC, merged