129/Meghna/Sree adds authconfirm controller and tests for authConfirm, authInit and fetchModes
Bahmni-Covid19/hip-service pull request #46
Opened 2021-03-17 06:41 UTC by SreeRanjani14

2021-03-17 08:04 UTC, praveenadayanand requested changes

2021-03-17 08:06 UTC, praveenadayanand commented on gatewayStubConfigurations/imposters/authConfirmResponse.ejs
> +var token = 'Bearer ' + config.request.headers.access_token;
the access_token has to be taken from the Authorization header as the access_token will not be present in an actual call to the gateway.

2021-03-17 08:07 UTC, praveenadayanand commented on gatewayStubConfigurations/imposters/authConfirmResponse.ejs
> +var reqBodyOnFetchModes = JSON.stringify(body1);
var name should reflect the API to be called which is auth/on-confirm

2021-03-17 08:07 UTC, praveenadayanand commented on gatewayStubConfigurations/imposters/authConfirmResponse.ejs
> +return {
the response should be done as a callback instead of return, see the ejs files for fetch-modes for reference

2021-03-17 10:42 UTC, MeghnaThoughtworks commented on test/In.ProjectEKA.HipServiceTest/Linkage/FetchModeControllerTest.cs
> +            var request = new FetchRequest("1234");
Oh its a test Praveena

2021-03-17 10:42 UTC, MeghnaThoughtworks commented on test/In.ProjectEKA.HipServiceTest/Linkage/FetchModeControllerTest.cs
> +            FetchModeMap.requestIdToFetchMode.Add(requestId, "12");
We did that to make the test work na cause its all mocked!

2021-03-18 06:18 UTC, MeghnaThoughtworks commented on gatewayStubConfigurations/imposters/authConfirmResponse.ejs
> +return {
In fetchmodes.ejs they are using return only

2021-03-18 06:23 UTC, MeghnaThoughtworks commented on gatewayStubConfigurations/imposters/authConfirmResponse.ejs
> +var reqBodyOnFetchModes = JSON.stringify(body1);
done

2021-03-18 06:23 UTC, MeghnaThoughtworks commented on gatewayStubConfigurations/imposters/authConfirmResponse.ejs
> +var token = 'Bearer ' + config.request.headers.access_token;
done

2021-03-18 06:24 UTC, MeghnaThoughtworks commented on test/In.ProjectEKA.HipServiceTest/Linkage/FetchModeControllerTest.cs
> +            var request = new FetchRequest("1234");
please check for auth-confirm so we can add for other controllers

2021-03-18 06:24 UTC, MeghnaThoughtworks commented on test/In.ProjectEKA.HipServiceTest/Linkage/FetchModeControllerTest.cs
> +            FetchModeMap.requestIdToFetchMode.Add(requestId, "12");
please check for auth-confirm so we can add for other controllers

2021-03-18 06:24 UTC, MeghnaThoughtworks commented on test/In.ProjectEKA.HipServiceTest/Linkage/FetchModeControllerTest.cs
> +                        client.SendDataToGateway(Constants.PATH_FETCH_AUTH_MODES,
please check for auth-confirm so we can add for other controllers

2021-03-18 09:00 UTC, MeghnaThoughtworks commented on test/In.ProjectEKA.HipServiceTest/Linkage/FetchModeControllerTest.cs
> +            var request = new FetchRequest("1234");
done for all 3

2021-03-18 09:01 UTC, MeghnaThoughtworks commented on test/In.ProjectEKA.HipServiceTest/Linkage/FetchModeControllerTest.cs
> +            FetchModeMap.requestIdToFetchMode.Add(requestId, "12");
done for all 3

2021-03-18 09:01 UTC, MeghnaThoughtworks commented on test/In.ProjectEKA.HipServiceTest/Linkage/FetchModeControllerTest.cs
> +                        client.SendDataToGateway(Constants.PATH_FETCH_AUTH_MODES,
done for all 3

2021-03-18 09:21 UTC, Nazeer-debug commented on src/In.ProjectEKA.HipService/User/UserController.cs
> +        }*/
if this comment put on a specific purpose okay, else remove it.

2021-03-18 09:55 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/User/UserController.cs
> +        }*/
It came from master rebase 😌

2021-03-18 09:59 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/User/UserController.cs
> +        }*/
We can do this under refactoring cause whoever wrote the auth-confirm forgot to remove this whole controller.

2021-03-18 10:00 UTC, Nazeer-debug commented on src/In.ProjectEKA.HipService/User/UserController.cs
> +        }*/
Okay Meghna

2021-03-18 11:37 UTC, closed without merging