138,139 | Meghna/Sree | Refactoring the UserAuth API's and adding tests for same
Bahmni-Covid19/hip-service pull request #48
Opened 2021-03-22 08:55 UTC by MeghnaThoughtworks

2021-03-22 09:20 UTC, Nazeer-debug approved these changes

2021-03-22 10:28 UTC, swatigogia2020 commented on gatewayStubConfigurations/imposters/authConfirmResponse.ejs
> +        "requestId": reqId
change this to be different than request.requestId

2021-03-22 10:28 UTC, swatigogia2020 approved these changes
Apart from one comment on the requestId returned. Looks good

2021-03-22 10:51 UTC, swatigogia2020 requested changes
change the id to "Bahmni" instead of clientid

2021-03-22 10:59 UTC, praveenadayanand requested changes

2021-03-22 10:59 UTC, praveenadayanand commented on src/In.ProjectEKA.HipLibrary/Patient/Model/ErrorCode.cs
> +        InvalidHealthId = 3432
Error code is same as HeartBeat

2021-03-22 10:59 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/UserAuth/Model/AuthInitQuery.cs
> +        public string purpose { get; } = Constants.FETCH_MODE_PURPOSE;
Can we rename FETCH_MODE_PURPOSE to something more generic like AUTH_PURPOSE ?

2021-03-22 10:59 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/UserAuth/Model/GatewayAuthConfirmRequestRepresentation.cs
> +        public string dump(Object o)
dump is implemented for logging purposes, isnt it? Can this be removed ?

2021-03-22 10:59 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthController.cs
> +        [Route(FETCH_MODES)]
Lets call all the API paths as PATH_*****

2021-03-22 10:59 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthController.cs
> +            Log.Information("On fetch mode request received." +
Lets use logger.log instead of Log.Info as we can apply log events

2021-03-22 10:59 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthController.cs
> +            var (gr, error) =
gr can be renamed as gatewayrepresentations***

2021-03-22 10:59 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthController.cs
> +        [Route(HIP_AUTH_CONFIRM)]
PATH_ suffix to the api path variable

2021-03-22 10:59 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthController.cs
> +        [HttpPost(ON_AUTH_CONFIRM)]
PATH_ suffix

2021-03-22 10:59 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthController.cs
> +            Log.Information($"Response RequestId:{request.resp.RequestId}");
Logger is preferred over Log.

2021-03-22 10:59 UTC, praveenadayanand commented on test/In.ProjectEKA.HipServiceTest/UserAuth/UserAuthControllerTest.cs
> +            var purpose = "KYC_AND_LINK";
Can use FETCH_MODE_PURPOSE instead a new var here, isnt it ?

2021-03-22 10:59 UTC, praveenadayanand commented on test/In.ProjectEKA.HipServiceTest/UserAuth/UserAuthControllerTest.cs
> +                new AuthModeFetch("KYC_AND_LINK", modes), null, new Resp(requestId.ToString()));
Use the same variable FETCH_MODE_PURPOSE everywhere

2021-03-22 11:21 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthService.cs
> +            var requester = new Requester(gatewayConfiguration.ClientId, FETCH_MODE_REQUEST_TYPE);
done

2021-03-22 11:27 UTC, MeghnaThoughtworks commented on gatewayStubConfigurations/imposters/authConfirmResponse.ejs
> +        "requestId": reqId
done

2021-03-22 11:28 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/UserAuth/Model/GatewayAuthConfirmRequestRepresentation.cs
> +        public string dump(Object o)
We don't want logs?

2021-03-22 11:41 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipLibrary/Patient/Model/ErrorCode.cs
> +        InvalidHealthId = 3432
done

2021-03-22 12:30 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/UserAuth/Model/GatewayAuthConfirmRequestRepresentation.cs
> +        public string dump(Object o)
I thought that the dump method was used only for a temporary dev logging. Is this dump method called anywhere ?

2021-03-23 05:20 UTC, Nazeer-debug commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthController.cs
> +        [Route(HIP_AUTH_CONFIRM)]
done

2021-03-23 05:21 UTC, Nazeer-debug commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthController.cs
> +        [HttpPost(ON_AUTH_CONFIRM)]
done

2021-03-23 05:21 UTC, Nazeer-debug commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthController.cs
> +            Log.Information($"Response RequestId:{request.resp.RequestId}");
done

2021-03-23 05:21 UTC, Nazeer-debug commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthController.cs
> +            Log.Information("On fetch mode request received." +
done

2021-03-23 05:21 UTC, Nazeer-debug commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthController.cs
> +        [Route(FETCH_MODES)]
done

2021-03-23 05:23 UTC, Nazeer-debug commented on src/In.ProjectEKA.HipService/UserAuth/Model/AuthInitQuery.cs
> +        public string purpose { get; } = Constants.FETCH_MODE_PURPOSE;
done

2021-03-23 05:28 UTC, Nazeer-debug commented on src/In.ProjectEKA.HipService/UserAuth/Model/GatewayAuthConfirmRequestRepresentation.cs
> +        public string dump(Object o)
The method is called in the UserAuthController

2021-03-23 05:30 UTC, Nazeer-debug commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthController.cs
> +            var (gr, error) =
done

2021-03-23 06:36 UTC, praveenadayanand approved these changes
Include bahmni config on appsettings.json as well as appsettings.dev.json

2021-03-23 06:44 UTC, merged