143 otp encryption
Bahmni-Covid19/hip-service pull request #53
Opened 2021-03-31 06:25 UTC by SreeRanjani14

2021-03-31 06:58 UTC, MeghnaThoughtworks requested changes

2021-03-31 06:58 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthController.cs
> +            gatewayAuthConfirmRequestRepresentation.credential.authCode = UserAuthService.GetDecodedOtp(authConfirmRequest);
Can we push this line to UserAuthService itself? The Service sole purpose was to return the correct gatewayRepresentations. Controllers should not handle decoding of the otp or any service related work.

2021-03-31 06:58 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthService.cs
> +        public static string GetDecodedOtp(AuthConfirmRequest authConfirmRequest)
make this private as well

2021-03-31 10:26 UTC, Nazeer-debug commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthController.cs
> +            gatewayAuthConfirmRequestRepresentation.credential.authCode = UserAuthService.GetDecodedOtp(authConfirmRequest);
We don't think so, anyhow we need to call that method even after moving that method to UserAuthService, UserAuthSerice is handling the response related things

2021-04-05 09:47 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthController.cs
> +            gatewayAuthConfirmRequestRepresentation.credential.authCode = UserAuthService.GetDecodedOtp(authConfirmRequest);
authCode is a part gatewayResponse, isn't it?

2021-04-05 09:49 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthController.cs
> +            gatewayAuthConfirmRequestRepresentation.credential.authCode = UserAuthService.GetDecodedOtp(authConfirmRequest);
I'm not talking about moving a method only the method call.

2021-04-05 09:53 UTC, MeghnaThoughtworks requested changes

2021-04-05 09:53 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthController.cs
> +            gatewayAuthConfirmRequestRepresentation.credential.authCode = UserAuthService.GetDecodedOtp(authConfirmRequest);
You are doing a service related work as in changing the authCode in controller? do you get that is my only reason. you can call that method inside the userAuthService.AuthConfirmResponse(authConfirmRequest) only.

2021-04-26 06:16 UTC, closed without merging