CORS configuration
Bahmni-Covid19/hip-service pull request #54
Opened 2021-04-05 09:26 UTC by Nazeer-debug

2021-04-06 09:38 UTC, MeghnaThoughtworks requested changes

2021-04-06 09:38 UTC, MeghnaThoughtworks commented on src/In.ProjectEKA.HipService/Common/Model/CorsConfiguration.cs
> +        //public static string AllowedOrigins { get; set; }
remove comment

2021-04-06 09:52 UTC, Nazeer-debug commented on src/In.ProjectEKA.HipService/Common/Model/CorsConfiguration.cs
> +        //public static string AllowedOrigins { get; set; }
Done

2021-04-07 09:47 UTC, MeghnaThoughtworks approved these changes

2021-04-08 09:07 UTC, swatigogia2020 approved these changes

2021-04-08 10:47 UTC, merged