Validates health Id in user auth flow
Bahmni-Covid19/hip-service pull request #58
Opened 2021-04-26 12:32 UTC by MeghnaThoughtworks

2021-04-27 12:41 UTC, praveenadayanand approved these changes

2021-04-27 12:41 UTC, swatigogia2020 approved these changes

2021-04-27 12:42 UTC, praveenadayanand commented
@MeghnaThoughtworks unittests are failing

2021-04-27 12:43 UTC, praveenadayanand requested changes
Unittest cases need to be fixed

2021-04-29 07:10 UTC, praveenadayanand approved these changes
Just for my understanding, is getting cmsuffix as part of the incoming health-id instead of a configuration, part of this story card ?

2021-04-29 07:15 UTC, MeghnaThoughtworks commented
> Just for my understanding, is getting cmsuffix as part of the incoming health-id instead of a configuration, part of this story card ?

I made the cmSuffix come from the config and not from the health Id as part of this card. So the opposite of what you said

2021-04-29 07:34 UTC, merged

2021-04-29 08:58 UTC, Mahesh-I commented on src/In.ProjectEKA.HipService/DataFlow/ErrorMessage.cs
> +                                                        " do not allow special character except dot (.)";
Do we really need error messages like these, usually these will be shown while creating a new health id right? Health Id is invalid or wrong  is enough i think