143| Sree Ranjani/Nazeer | Adds Base64 encode for the auth code
Bahmni-Covid19/hip-service pull request #62
Opened 2021-05-12 05:13 UTC by SreeRanjani14

2021-05-18 08:26 UTC, praveenadayanand requested changes

2021-05-18 08:26 UTC, praveenadayanand commented on src/In.ProjectEKA.HipService/UserAuth/UserAuthService.cs
> +            this.logger = logger;
is logger used anywhere in this code?

2021-05-20 05:14 UTC, swatigogia2020 approved these changes
Remove the logger if not used

2021-05-20 06:39 UTC, praveenadayanand approved these changes

2021-05-20 07:09 UTC, MeghnaThoughtworks requested changes
Please add tests for new code

2021-05-20 10:45 UTC, Nazeer-debug commented
> Please add tests for new code

Tests for the new method or auth confirm flow?

2021-05-24 09:42 UTC, MeghnaThoughtworks approved these changes

2021-05-24 10:35 UTC, merged