276|Nazeer/Tazeen| Refactors Add-context API and implemented the new …
Bahmni-Covid19/hip-service pull request #69
Opened 2021-08-02 05:26 UTC by Nazeer-debug

…Custom API to call Add-context or notify-context based on the linked contexts

2021-08-03 05:07 UTC, swatigogia2020 requested changes

2021-08-03 05:45 UTC, Nazeer-debug commented on src/In.ProjectEKA.HipService/Common/Model/HIPReference.cs
> -        public HIPReference(string id)
we created this in the first place

2021-08-05 10:51 UTC, swatigogia2020 requested changes

2021-08-05 10:51 UTC, swatigogia2020 commented on src/In.ProjectEKA.HipService/Link/CareContextController.cs
> +                    "Request for auth-init to gateway: {@GatewayResponse}",
add-contexts, instead of auth-init

2021-08-09 05:30 UTC, swatigogia2020 approved these changes

2021-08-10 05:52 UTC, closed without merging