276 new context
Bahmni-Covid19/hip-service pull request #71
Opened 2021-08-10 05:59 UTC by Nazeer-debug

2021-08-19 05:08 UTC, swatigogia2020 requested changes

2021-08-19 05:08 UTC, swatigogia2020 commented on src/In.ProjectEKA.HipService/Link/CareContextController.cs
> +                    "Request for auth-init to gateway: {@GatewayResponse}",
add-context, instead of auth-init

2021-08-19 05:08 UTC, swatigogia2020 commented on src/In.ProjectEKA.HipService/Link/CareContextController.cs
> +                logger.Log(LogLevel.Information, LogEvents.AddContext, $"cmSuffix: {{cmSuffix}}," +
I do not see authorisation/cookie check for this method

2021-08-19 05:08 UTC, swatigogia2020 commented on src/In.ProjectEKA.HipService/Link/CareContextController.cs
> +            foreach (var context in newContextRequest.CareContexts)
no authorisation/cookie check for this API

2021-08-23 09:40 UTC, swatigogia2020 approved these changes

2021-08-24 06:23 UTC, rohit-yawalkar commented on src/In.ProjectEKA.HipService/Link/CareContextController.cs
> +                                                                     $"requestId: {{requestId}}",
@Nazeer-debug Can we remove this log?

2021-08-25 07:54 UTC, swatigogia2020 commented on src/In.ProjectEKA.HipService/Link/CareContextController.cs
> +                                                                     $"requestId: {{requestId}}",
@rohit-yawalkar lets have this log now, as these help in debugging

2021-08-25 08:19 UTC, rohit-yawalkar approved these changes

2021-08-25 11:02 UTC, merged