304 update accesstoken
Bahmni-Covid19/hip-service pull request #72
Opened 2021-08-17 09:27 UTC by Nazeer-debug

2021-08-19 05:36 UTC, swatigogia2020 requested changes

2021-08-19 05:36 UTC, swatigogia2020 commented on gatewayStubConfigurations/imposters/authConfirmResponse.ejs
>          "validity": {
have dummy string, instead of an access token

2021-08-19 05:36 UTC, swatigogia2020 commented on src/In.ProjectEKA.HipService/Common/Constants.cs
> +        public const string HIP_URL = "https://ndhm-dev.bahmni-covid19.in/hiprovider";
make it a configuration

2021-08-20 09:15 UTC, Nazeer-debug commented on gatewayStubConfigurations/imposters/authConfirmResponse.ejs
>          "validity": {
Hello Swati, we need an access token for local testing it's better to keep it

2021-08-23 09:45 UTC, swatigogia2020 approved these changes

2021-08-25 08:23 UTC, rohit-yawalkar approved these changes

2021-08-25 11:03 UTC, merged