156/sms notification
Bahmni-Covid19/hip-service pull request #73
Opened 2021-08-18 10:40 UTC by tazeen7

2021-08-19 05:18 UTC, swatigogia2020 requested changes

2021-08-19 05:18 UTC, swatigogia2020 commented on test/In.ProjectEKA.HipServiceTest/SmsNotification/SmsNotificationControllerTest.cs
> +    }
add more test cases

2021-08-24 06:15 UTC, rohityawalkar04 commented on src/In.ProjectEKA.HipService/SmsNotification/SmsNotificationController.cs
> +            // }
Please remove the comments if not needed

2021-08-24 06:18 UTC, rohit-yawalkar commented on src/In.ProjectEKA.HipService/SmsNotification/SmsNotificationController.cs
> +            //     {
@tazeen7 Please remove the comments.

2021-08-24 06:36 UTC, tazeen7 commented on src/In.ProjectEKA.HipService/SmsNotification/SmsNotificationController.cs
> +            //     {
Sure

2021-08-24 07:29 UTC, rohit-yawalkar approved these changes

2021-08-25 07:52 UTC, swatigogia2020 approved these changes

2021-09-02 05:42 UTC, merged