366|Sameera|Nazeer|Adds remove healthId based on the action
Bahmni-Covid19/hip-service pull request #81
Opened 2021-09-24 11:37 UTC by Nazeer-debug

2021-09-28 06:19 UTC, swatigogia2020 requested changes

2021-09-28 06:19 UTC, swatigogia2020 commented on src/In.ProjectEKA.HipService/Patient/PatientController.cs
> +        public AcceptedResult PatientOnNotify(HipPatientNotifyConfirmation confirmation)
we call on-notify on gateway, listener is not required

2021-09-28 06:20 UTC, tazeen7 approved these changes

2021-09-28 06:56 UTC, Nazeer-debug commented on src/In.ProjectEKA.HipService/Patient/PatientController.cs
> +        public AcceptedResult PatientOnNotify(HipPatientNotifyConfirmation confirmation)
done

2021-09-28 07:10 UTC, swatigogia2020 approved these changes

2021-09-28 07:36 UTC, rohit-yawalkar approved these changes

2021-09-30 11:26 UTC, rohit-yawalkar approved these changes

2021-09-30 12:51 UTC, tazeen7 approved these changes

2021-10-01 04:31 UTC, merged